---
Title: "Protected Information"
output:
  fidelius::html_password_protected:
    output_format:
      rmarkdown::html_document:
        toc: true
        toc_depth: 2
        toc_float: true
        number_sections: false
        code_folding: hide
        df_print: paged
        code_download: true
        theme: cerulean
    password: "test"
    hint: "The password is test"
fontsize: 12pt
---


```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      error = TRUE)
```
<font size = 4>

# To-Do List

* Trim the shrubs around the house to clean up the yard
  * Think of something to replace the shrub that Ben and Melissa destroyed in Fall of 2022
  * Buy a chainsaw or electric trimmer

# Butte House Information

## Wifi 

* Wifi name: `Ruso`
  * password: `Rusogirl1` 

# Helpful Contacts

## Mowing in Town: Amy Nechiperenko {#amyNechiperenko}

Amy has mowed for us for many years and is the daughter of Jim's best friend, Ronnie Nechiperenko.
Amy is also a good contact for other things happening in Butte.


* **Phone:** `701-626-1104`

## Electic/Plumber?: Pat Haugen

Possibly electrician or plumber who did stuff at Butte house basement.
Was paid to do work on 7/22/22.
He has also worked at Ducks, and Nancy Ostrom went to Nashville with him.

* **Phone:** `Unknown`

## Mowing at Ducks: Dana Anderson

Mows at Ducks and is paid $300 bucks for the whole summer in 2022.

* **Phone:** `Unknown`

## Kathy Schatz

Owned the bar in Butte for many years and has great hommade donuts.
Cathy is also the contact for the sewer bill in Butte.
Her daughter is [Amy Nechiperenko](#amyNechiperenko)

* **Phone:** `701-626-7177` or `701-626-7386`
  * Information found here: https://www.anamoose.com/lodges.php


## Opening up the house

Place holder section on opening up the house.

1. Place instructions on closing down the house
1. Video of how to open up house

## Closing Down the house

Place holder section on closing down the house.

1. Place instructions on closing down the house
1. Video of how to close down the house up house

# Log of Past projects at Butte house

## Garage

* Fall 2021
  * New garage door put in by Joe Legg

## House

* Summer 2021
  * New electric and plumbing set up downstairs
  * New water heater

* 2017-2019??
  * Hyme and his group did a number of projects including
    * Roof on the house
    * Put rocks in the basement
    * Dug under the house and poured cement to support the house
    * New kitchen ceiling
    * Fixed cracks in walls


# Ducks Landing Information

## Helpful Notes

* The electric will trip if all heaters are on at same time
* There is a large draft that comes thorugh the south front door
* It is very helpful to have mice poison ready to thow downstairs.
Mice really work their way in there in the winter.

## Setting up TV

* There is a tailgater satelite that we keep in the house at Butte.
This can be put outside and you can pay to have it activated for a month at a time by calling.

## Opening up the cabin

Place holder section on opening up the cabin.

1. Place instructions on closing down the cabin
1. Video of how to open up cabin

## Closing Down the cabin

Place holder section on closing down the cabin.

1. Place instructions on closing down the cabin
1. Video of how to close down the cabin up cabin

</font>