---
title: "Land Description"
output_format:
   rmarkdown::html_document:
      toc: true
      toc_depth: 2
      toc_float: true
      number_sections: false
      code_folding: hide
      df_print: paged
      code_download: true
      theme: readable
---


```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      error = TRUE)
```

# This will contain information on land

This can include: 

1. Where the land is located
1. Who is renting it
1. When CRP dates are up for renewal

# Land File

<embed src="Files/LandPlats.pdf" width="1000" height="600">


## First Farm

The first farm includes the following sections.

* **Section 32:**
  * W^1/2^
  * NE^1/4^
  * NW^1/4^
  * SW^1/4^
  * SE^1/4^
* **Section 29**
  * S^1/2^ (Gravel Pit)
  * SW^1/4^ (Gravel Pit)
  

## Ducks Landing

Ducks landing contains the following sections. 

* **Section 18:** Ducks landing and surrounding pasture land
  * E^1/2^NW^1/4^ Lots 1 and 2
  * Lots 3 and 4 E1⁄2SW1⁄4
  * SW^1/4^
  * SE^1/4^ (Ben believes the cabin sits on this piece)
* **Section 19:** "Dead" area south of the Ducks landing cabin
  * NW^1/4^NE^1/4^
  * NE^1/4^NW^1/4^
  * NW^1/4^NW^1/4^
  
## Home Farm

This contains the original homestead that Sam Lakoduk (Eddies dad?) homesteaded on.

* **Section 24:** 
  * NE^1/4^
  
## North Farm

This is the site of the "stadium" and has had great deer hunting over the years.

* **Section 13:** (Needs some work and looks to be incorrect)
  * NE^1/4^
  * E^1/2^NW^1/4^
  * NE^1/4^SE^1/4^
  * SE^1/4^SE^1/4^ (This may be incorrect)
  
## Turkey Farm

* **Section 12**
  * S^1/2^SE^1/4^
  
## Flats

This has traditionally been pasture land.

* **Section 1**
  * E^1/2^SE^1/4^

* **Section 6:**
  * E^1/2^1⁄2SW^1/4^, Lots 6 and 7

* **Section 7:**
  * NE^1/4^
  * E^1/2^NW^1/4^, Lots 1 and 2
  
* **Section 12:** 
  * NE^1/4^NE^1/4^



